name: android_audio_plugin
description: Plugin for turning Android sound on and off
version: 0.0.1
homepage: https://github.com/watayouxiang/android_audio_plugin

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.watayouxiang.android_audio_plugin
        pluginClass: AndroidAudioPlugin

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  platform: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


